### ISSUE TITLE
Parsing of my valid MRZ fails

### ISSUE THREAD

**Issue by v-morlock** [asmarques/mrtd#5]
Hi, 

this library fails to parse the MRZ of my passport, i think the reason is that position 43 in line two is a < instead of a number. This is valid as described here if no "personal number" is being assigned (germany for example)

https://en.wikipedia.org/wiki/Machine-readable_passport

**Comment by asmarques** [comment]
Validation no longer fails if both optional data and corresponding check digit fields contain only the filler char `<`. This should fix the issue with your passport.

**Comment by v-morlock** [comment]
Hi, thanks a lot for fixing, works perfectly fine now! Do you plan to release a new version on crates.io soonish?

**Comment by asmarques** [comment]
Yes, `v0.5.1` is now available on crates.io with this fix.
